Repository sanity-io/sanity, pull requests merged in 2018-03, with the labels that each got.

#406 [mutator] Update mutator readme
  packages/@sanity/mutator/README.md
Labels: package/mutator

#657 [components] Background color on closeButton
  packages/@sanity/components/src/dialogs/styles/FullscreenDialog.css
Labels: No docs needed

#656 [components] Make arrow ignore pointer-event and clicks the select
  packages/@sanity/components/src/selects/styles/DefaultSelect.css
Labels: No docs needed

#658 [components] Add description to booleans
  packages/@sanity/components/src/toggles/Checkbox.js
  packages/@sanity/components/src/toggles/Switch.js
  packages/@sanity/components/src/toggles/styles/Checkbox.css
  packages/@sanity/components/src/toggles/styles/Switch.css
  packages/@sanity/form-builder/src/inputs/BooleanInput.js
Labels: No docs needed

#661 [desk-tool] Centering editor spinners
  packages/@sanity/desk-tool/src/pane/Editor.js
  packages/@sanity/desk-tool/src/pane/styles/Editor.css
Labels: No docs needed

#660 [components] Remove deprecated kind secondary button
  packages/@sanity/components/src/buttons/styles/DefaultButton.css
  packages/@sanity/components/src/dialogs/ConfirmDialog.js
  packages/@sanity/desk-tool/src/components/ConfirmDelete.js
Labels: No docs needed

#667 [components] No pointer-events on arrow. pointer events on functions
  packages/@sanity/components/src/selects/styles/DefaultSelect.css
  packages/@sanity/components/src/selects/styles/SearchableSelect.css
Labels: No docs needed

#669 [desk-tool] Force auto height on ListView on mobile
  packages/@sanity/desk-tool/src/pane/styles/ListView.css
Labels: No docs needed

#668 [desk-tool] Clean up sync spinners
  packages/@sanity/desk-tool/src/pane/Editor.js
  packages/@sanity/desk-tool/src/pane/styles/Editor.css
Labels: No docs needed

#678 [form-builder] Correct smiley, no animation and hide on mobile
  packages/@sanity/form-builder/src/inputs/common/UploadPlaceholder.js
  packages/@sanity/form-builder/src/inputs/common/styles/UploadPlaceholder.css
Labels: No docs needed

#681 [default-layout] Fixes white stripe glitch on action modal
  packages/@sanity/components/src/dialogs/styles/DefaultDialog.css
  packages/@sanity/default-layout/src/components/ActionModal.js
  packages/@sanity/default-layout/src/components/styles/ActionModal.css
Labels: No docs needed

#680 Fix/buttons and fullscreen tweaks
  packages/@sanity/components/src/buttons/styles/DefaultButton.css
  packages/@sanity/components/src/dialogs/styles/FullscreenDialog.css
  packages/@sanity/desk-tool/src/pane/styles/Editor.css
Labels: No docs needed

#679 [base] Background on root on text-input
  packages/@sanity/base/src/styles/forms/text-input.css
Labels: No docs needed

#685 [form-builder] Support collapsible objects with default limit
  packages/@sanity/form-builder/src/inputs/ObjectInput/ObjectInput.js
  packages/test-studio/schemas/objects.js
  packages/test-studio/schemas/recursiveObject.js
  packages/test-studio/schemas/schema.js
Labels: Docs needed
